apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: talos-state-metrics
  namespace: monitoring
  labels:
    app.kubernetes.io/name: talos-state-metrics
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: talos-state-metrics
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
